/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoppingoline.View;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import shoppingoline.MainJFrame;
import shoppingoline.Service.Impl.MainServiceImpl;
import shoppingoline.Service.MainService;
import shoppingoline.Utils.ActionUtils;
import shoppingoline.model.CartDTO;
import shoppingoline.model.ProductDTO;

/**
 *
 * @author ngocanh
 */
public class DetailProductPanel extends javax.swing.JPanel {

    MainJFrame mainJFrame;
    String id = "";
    ActionUtils actionUtils = new ActionUtils();
    ProductDTO product;
    MainService mainService = new MainServiceImpl();

    /**
     * Creates new form DetailProductPanel
     */
    public DetailProductPanel(ProductDTO product, MainJFrame mainJFrame) {
        initComponents();
        // get detail product from db
        this.mainJFrame = mainJFrame;
        this.product = product;
        id = product.getId();
        //Product data = new Product("Hoa Hong"+id);
        txtTitle.setText(product.getTitle());
        txtPrice.setText(product.getPrice());
        actionUtils.fillImageOnline(product.getUrlImage(), txtImage, 200, 180);
        dialogDetail.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                DetailProductPanel.this.mainJFrame.setEnabled(true);
                DetailProductPanel.this.mainJFrame.setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDetail = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        txtDetailImage = new javax.swing.JLabel();
        txtDetailTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetailDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtDetailQuantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDetailPrice = new javax.swing.JLabel();
        btbAddToCartDetail = new javax.swing.JButton();
        panellmage = new javax.swing.JPanel();
        txtImage = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDetail = new javax.swing.JButton();
        txtAddToCart = new javax.swing.JButton();
        txtPrice = new javax.swing.JLabel();

        dialogDetail.setAlwaysOnTop(true);
        dialogDetail.setSize(new java.awt.Dimension(800, 600));
        dialogDetail.setType(java.awt.Window.Type.POPUP);

        txtDetailTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDetailTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDetailDesc.setColumns(20);
        txtDetailDesc.setLineWrap(true);
        txtDetailDesc.setRows(20);
        txtDetailDesc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDetailDesc);

        jLabel3.setText("Số lượng còn lại:");

        jLabel4.setText("Đơn giá");

        btbAddToCartDetail.setText("Add to Cart");
        btbAddToCartDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAddToCartDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDetailTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDetailImage, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDetailPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDetailQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btbAddToCartDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDetailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDetailImage, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDetailQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btbAddToCartDetail)
                        .addGap(218, 218, 218))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogDetailLayout = new javax.swing.GroupLayout(dialogDetail.getContentPane());
        dialogDetail.getContentPane().setLayout(dialogDetailLayout);
        dialogDetailLayout.setHorizontalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogDetailLayout.setVerticalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(296, 170));

        panellmage.setMaximumSize(new java.awt.Dimension(300, 200));
        panellmage.setLayout(new java.awt.BorderLayout());
        panellmage.add(txtImage, java.awt.BorderLayout.CENTER);

        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtDetail.setText("Detail");
        txtDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDetailMouseEntered(evt);
            }
        });
        txtDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailActionPerformed(evt);
            }
        });

        txtAddToCart.setText("Add to cart");
        txtAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtAddToCart)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddToCart)
                    .addComponent(txtDetail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panellmage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panellmage, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddToCartActionPerformed
        CartDTO c = new CartDTO();
        c.setCustomerId(MainJFrame.currentUserId);
        c.setProductId(this.product.getId());
        c.setQuantity(1);
        if (mainService.insertCart(c)) {
            JOptionPane.showMessageDialog(this, "Thêm vào giỏ hàng thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Thêm vào giỏ hàng thất bại");

        }

    }//GEN-LAST:event_txtAddToCartActionPerformed

    private void txtDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailActionPerformed
        showDetail(this.product);   // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailActionPerformed

    private void txtDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetailMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDetailMouseEntered

    private void btbAddToCartDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAddToCartDetailActionPerformed
        CartDTO c = new CartDTO();
        c.setCustomerId(MainJFrame.currentUserId);
        c.setProductId(this.product.getId());
        c.setQuantity(1);
        if (mainService.insertCart(c)) {
            JOptionPane.showMessageDialog(this, "Thêm vào giỏ hàng thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Thêm vào giỏ hàng thất bại");
        }
    }//GEN-LAST:event_btbAddToCartDetailActionPerformed

    private void showDetail(ProductDTO product) {
        txtDetailTitle.setText(product.getTitle());
        txtDetailQuantity.setText(product.getQuantity() + "");
        txtDetailPrice.setText(product.getPrice() + "");
        actionUtils.fillImageOnline(product.getUrlImage(), txtDetailImage, 400, 250);
        txtDetailDesc.setText(product.getDesc());
        dialogDetail.setLocation(this.mainJFrame.getLocation());
        dialogDetail.setVisible(true);
        this.mainJFrame.setEnabled(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAddToCartDetail;
    private javax.swing.JDialog dialogDetail;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panellmage;
    private javax.swing.JButton txtAddToCart;
    private javax.swing.JButton txtDetail;
    private javax.swing.JTextArea txtDetailDesc;
    private javax.swing.JLabel txtDetailImage;
    private javax.swing.JLabel txtDetailPrice;
    private javax.swing.JLabel txtDetailQuantity;
    private javax.swing.JLabel txtDetailTitle;
    private javax.swing.JLabel txtImage;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
