/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoppingoline.View;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import shoppingoline.MainJFrame;
import shoppingoline.Service.Impl.MainServiceImpl;
import shoppingoline.Service.MainService;
import shoppingoline.Utils.ActionUtils;
import shoppingoline.Utils.OderStatusType;
import shoppingoline.model.OrderDTO;
import shoppingoline.model.OrderDetailDTO;

/**
 *
 * @author choco
 */
public class OrderPanel extends javax.swing.JPanel {

    ActionUtils actionUtils = new ActionUtils();
    JPopupMenu popupMenu = new JPopupMenu();
    DefaultTableModel orderTableModel;
    DefaultTableModel orderDetailTableModel;
    MainService mainService = new MainServiceImpl();
    String orderSelectedId = "";
    MainJFrame mainJFrame;
    List<OrderDTO> orders = new ArrayList<>();

    /**
     * Creates new form OrderPanel
     */
    public OrderPanel(MainJFrame mainJ) {
        initComponents();
        this.mainJFrame = mainJ;
        orderTableModel = (DefaultTableModel) tableOrder.getModel();
        orderDetailTableModel = (DefaultTableModel) tableDetail.getModel();
        // ẩn cột code(id)

        tableOrder.getColumnModel().getColumn(0).setMaxWidth(0);
        tableOrder.getColumnModel().getColumn(0).setMinWidth(0);
        tableOrder.getColumnModel().getColumn(1).setMaxWidth(100);
        tableDetail.getColumnModel().getColumn(0).setMaxWidth(100);
        tableOrder.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent evt) {
                int r = tableOrder.rowAtPoint(evt.getPoint());
                if (r >= 0 && r < tableOrder.getRowCount()) {
                    tableOrder.setRowSelectionInterval(r, r);
                } else {
                    tableOrder.clearSelection();
                }
            }

        });

        orders = mainService.getOrderByCus(MainJFrame.currentUserId);
        if (orders != null && !orders.isEmpty()) {
            // show bangr order
            showTable(orders);
        }
        dialogDetail.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                OrderPanel.this.mainJFrame.setEnabled(true);
                OrderPanel.this.mainJFrame.setVisible(true);
            }
        });

    }

    public void showTable(List<OrderDTO> list) {
        orderTableModel.setRowCount(0);
        int no = 1;
        for (OrderDTO lts : list) {
            orderTableModel.addRow(new Object[]{
                lts.getId(), no++, OderStatusType.valueOf(lts.getStatus()).getDesc(), lts.getCreatedAt(), actionUtils.doubleToDecimal(Double.parseDouble(lts.getTotal()))
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDetail = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        dialogDetail.setSize(new java.awt.Dimension(462, 297));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Order Detail");

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Product Name", "Quantity", "Price", "Money"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDetail);

        javax.swing.GroupLayout dialogDetailLayout = new javax.swing.GroupLayout(dialogDetail.getContentPane());
        dialogDetail.getContentPane().setLayout(dialogDetailLayout);
        dialogDetailLayout.setHorizontalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        dialogDetailLayout.setVerticalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Order");

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "#", "Status", "Date", "Total"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrder);

        jLabel3.setText("Click right mouse to view detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            orderSelectedId = "";

            int i = tableOrder.getSelectedRow();
            orderSelectedId = orderTableModel.getValueAt(i, 0).toString();
            // show detail

            Optional<OrderDTO> orderDetail = orders.stream().filter(c -> c.getId().equalsIgnoreCase(orderSelectedId)).findFirst();
            if (orderDetail.isPresent()) {
                showTableDetail(orderDetail.get().getOrderDetailDTO());
                dialogDetail.setLocation(this.getLocation());
                dialogDetail.setVisible(true);
                this.mainJFrame.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tableOrderMouseClicked

    public void showTableDetail(List<OrderDetailDTO> list) {
        orderDetailTableModel.setRowCount(0);
        int no = 1;
        for (OrderDetailDTO lts : list) {
            orderDetailTableModel.addRow(new Object[]{
                no++, lts.getProductName(), lts.getQuantity(),
                actionUtils.doubleToDecimal(Double.parseDouble(lts.getPrice())),
                actionUtils.doubleToDecimal(lts.getQuantity() * Double.parseDouble(lts.getPrice()))
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tableOrder;
    // End of variables declaration//GEN-END:variables
}
