/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoppingoline.View;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import shoppingoline.MainJFrame;
import shoppingoline.Service.Impl.MainServiceImpl;
import shoppingoline.Service.MainService;
import shoppingoline.Utils.ActionUtils;
import shoppingoline.model.ProductDTO;

/**
 *
 * @author ngocanh
 */
public class ProductPanel extends javax.swing.JPanel {

    ActionUtils actionUtils = new ActionUtils();
    MainService mainService = new MainServiceImpl();
    private MainJFrame mainJFrame;
    private int offset = 0;

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel(MainJFrame mainJframe) {
        initComponents();
        this.mainJFrame = mainJframe;
        List<String> listType = mainService.getAllCategory();
        formatBox(boxType, listType);
        search("", "ALL", 0);

    }

    private void search(String name, String type, int offset) {
        List<ProductDTO> products = mainService.searchProduct(name, type, offset);
        int sizeProduct = products.size();
        actionUtils.showPanel(panelProduct1, new JPanel());
        actionUtils.showPanel(panelProduct2, new JPanel());
        actionUtils.showPanel(panelProduct3, new JPanel());
        actionUtils.showPanel(panelProduct4, new JPanel());
        actionUtils.showPanel(panelProduct5, new JPanel());
        actionUtils.showPanel(panelProduct6, new JPanel());

        for (int i = 0; i < sizeProduct; i++) {
            DetailProductPanel p = new DetailProductPanel(products.get(i), this.mainJFrame);
            switch (i) {
                case 0: {
                    actionUtils.showPanel(panelProduct1, p);
                    break;
                }
                case 1: {
                    actionUtils.showPanel(panelProduct2, p);
                    break;
                }
                case 2: {
                    actionUtils.showPanel(panelProduct3, p);
                    break;
                }
                case 3: {
                    actionUtils.showPanel(panelProduct4, p);
                    break;
                }
                case 4: {
                    actionUtils.showPanel(panelProduct5, p);
                    break;
                }
                case 5: {
                    actionUtils.showPanel(panelProduct6, p);
                    break;
                }

            }
        }

    }

    public void formatBox(JComboBox box, List<String> values) {
        box.removeAllItems();
        box.addItem("ALL");
        values.forEach(t -> {
            box.addItem(t);

        });
        box.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProduct1 = new javax.swing.JPanel();
        panelProduct2 = new javax.swing.JPanel();
        panelProduct3 = new javax.swing.JPanel();
        panelProduct4 = new javax.swing.JPanel();
        panelProduct5 = new javax.swing.JPanel();
        panelProduct6 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boxType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(890, 459));

        panelProduct1.setBackground(new java.awt.Color(255, 204, 0));
        panelProduct1.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct1.setLayout(new java.awt.BorderLayout());

        panelProduct2.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct2.setLayout(new java.awt.BorderLayout());

        panelProduct3.setBackground(new java.awt.Color(51, 255, 51));
        panelProduct3.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct3.setLayout(new java.awt.BorderLayout());

        panelProduct4.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct4.setLayout(new java.awt.BorderLayout());

        panelProduct5.setBackground(new java.awt.Color(255, 51, 51));
        panelProduct5.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct5.setLayout(new java.awt.BorderLayout());

        panelProduct6.setPreferredSize(new java.awt.Dimension(296, 170));
        panelProduct6.setLayout(new java.awt.BorderLayout());

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxType, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addComponent(panelProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), 0);
        offset = 0;
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        offset += 1;
        search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), offset);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        offset -= 1;
        if (offset >= 0) {

            search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), offset);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxType;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JPanel panelProduct2;
    private javax.swing.JPanel panelProduct3;
    private javax.swing.JPanel panelProduct4;
    private javax.swing.JPanel panelProduct5;
    private javax.swing.JPanel panelProduct6;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
