/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoppingoline.View;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import shoppingoline.MainJFrame;
import shoppingoline.Service.Impl.MainServiceImpl;
import shoppingoline.Service.MainService;
import shoppingoline.Utils.ActionUtils;
import shoppingoline.model.ProductDTO;

/**
 *
 * @author choco
 */
public class PrPanel extends javax.swing.JPanel {

    ActionUtils actionUtils = new ActionUtils();
    MainService mainService = new MainServiceImpl();
    private MainJFrame mainJFrame;
    private int offset = 0;

    /**
     * Creates new form Products
     */
    public PrPanel(MainJFrame mainJframe) {
        initComponents();
        initComponents();
        this.mainJFrame = mainJframe;
        List<String> listType = mainService.getAllCategory();
        formatBox(boxType, listType);
        search("", "ALL", 0);
    }

    private void search(String name, String type, int offset) {
        List<ProductDTO> products = mainService.searchProduct(name, type, offset);
        int sizeProduct = products.size();
        actionUtils.showPanel(panelProduct1, new JPanel());
        actionUtils.showPanel(panelProduct2, new JPanel());
        actionUtils.showPanel(panelProduct3, new JPanel());
        actionUtils.showPanel(panelProduct4, new JPanel());
        actionUtils.showPanel(panelProduct5, new JPanel());
        actionUtils.showPanel(panelProduct6, new JPanel());

        for (int i = 0; i < sizeProduct; i++) {
            DetailProductPanel p = new DetailProductPanel(products.get(i), this.mainJFrame);
            switch (i) {
                case 0: {
                    actionUtils.showPanel(panelProduct1, p);
                    break;
                }
                case 1: {
                    actionUtils.showPanel(panelProduct2, p);
                    break;
                }
                case 2: {
                    actionUtils.showPanel(panelProduct3, p);
                    break;
                }
                case 3: {
                    actionUtils.showPanel(panelProduct4, p);
                    break;
                }
                case 4: {
                    actionUtils.showPanel(panelProduct5, p);
                    break;
                }
                case 5: {
                    actionUtils.showPanel(panelProduct6, p);
                    break;
                }

            }
        }

    }

    public void formatBox(JComboBox box, List<String> values) {
        box.removeAllItems();
        box.addItem("ALL");
        values.forEach(t -> {
            box.addItem(t);

        });
        box.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelProduct2 = new javax.swing.JPanel();
        panelProduct5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelProduct1 = new javax.swing.JPanel();
        panelProduct4 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelProduct3 = new javax.swing.JPanel();
        panelProduct6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        boxType = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(890, 459));
        setMinimumSize(new java.awt.Dimension(890, 459));
        setPreferredSize(new java.awt.Dimension(890, 459));

        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(290, 370));
        jPanel2.setMinimumSize(new java.awt.Dimension(290, 370));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 370));

        panelProduct2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct2.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct2.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct2.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct2.setLayout(new java.awt.BorderLayout());

        panelProduct5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct5.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct5.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct5.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct5.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addComponent(panelProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(290, 370));

        panelProduct1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct1.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct1.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct1.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct1.setLayout(new java.awt.BorderLayout());

        panelProduct4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct4.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct4.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct4.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(297, 370));

        panelProduct3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct3.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct3.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct3.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct3.setLayout(new java.awt.BorderLayout());

        panelProduct6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProduct6.setMaximumSize(new java.awt.Dimension(290, 182));
        panelProduct6.setMinimumSize(new java.awt.Dimension(290, 182));
        panelProduct6.setPreferredSize(new java.awt.Dimension(290, 182));
        panelProduct6.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addComponent(panelProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(boxType)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), 0);
        offset = 0;
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        offset += 1;
        search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), offset);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        offset -= 1;
        if (offset >= 0) {

            search(txtSearch.getText().trim(), boxType.getSelectedItem().toString(), offset);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxType;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JPanel panelProduct2;
    private javax.swing.JPanel panelProduct3;
    private javax.swing.JPanel panelProduct4;
    private javax.swing.JPanel panelProduct5;
    private javax.swing.JPanel panelProduct6;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
