# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: visual_search.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'visual_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13visual_search.proto\x12\rvisual_search\"6\n\x13VisualSearchRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"L\n\x14VisualSearchResponse\x12\x1a\n\x12similar_image_urls\x18\x01 \x03(\t\x12\x18\n\x10similar_text_ids\x18\x02 \x03(\x05\x32h\n\x13VisualSearchService\x12Q\n\x06Search\x12\".visual_search.VisualSearchRequest\x1a#.visual_search.VisualSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visual_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VISUALSEARCHREQUEST']._serialized_start=38
  _globals['_VISUALSEARCHREQUEST']._serialized_end=92
  _globals['_VISUALSEARCHRESPONSE']._serialized_start=94
  _globals['_VISUALSEARCHRESPONSE']._serialized_end=170
  _globals['_VISUALSEARCHSERVICE']._serialized_start=172
  _globals['_VISUALSEARCHSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
