package visual_search;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visual_search.proto

public final class VisualSearchOuterClass {
  private VisualSearchOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisualSearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visual_search.VisualSearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string image_url = 1;</code>
     * @return The imageUrl.
     */
    java.lang.String getImageUrl();
    /**
     * <code>string image_url = 1;</code>
     * @return The bytes for imageUrl.
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();

    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code visual_search.VisualSearchRequest}
   */
  public static final class VisualSearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:visual_search.VisualSearchRequest)
      VisualSearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualSearchRequest.newBuilder() to construct.
    private VisualSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualSearchRequest() {
      imageUrl_ = "";
      text_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisualSearchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_visual_search_VisualSearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_visual_search_VisualSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VisualSearchOuterClass.VisualSearchRequest.class, VisualSearchOuterClass.VisualSearchRequest.Builder.class);
    }

    public static final int IMAGE_URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object imageUrl_;
    /**
     * <code>string image_url = 1;</code>
     * @return The imageUrl.
     */
    @java.lang.Override
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string image_url = 1;</code>
     * @return The bytes for imageUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, imageUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, imageUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VisualSearchOuterClass.VisualSearchRequest)) {
        return super.equals(obj);
      }
      VisualSearchOuterClass.VisualSearchRequest other = (VisualSearchOuterClass.VisualSearchRequest) obj;

      if (!getImageUrl()
          .equals(other.getImageUrl())) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VisualSearchOuterClass.VisualSearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visual_search.VisualSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visual_search.VisualSearchRequest)
        VisualSearchOuterClass.VisualSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_visual_search_VisualSearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_visual_search_VisualSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VisualSearchOuterClass.VisualSearchRequest.class, VisualSearchOuterClass.VisualSearchRequest.Builder.class);
      }

      // Construct using visual_search.visual_search.VisualSearch.VisualSearchRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        imageUrl_ = "";

        text_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_visual_search_VisualSearchRequest_descriptor;
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchRequest getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchRequest build() {
        VisualSearchOuterClass.VisualSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchRequest buildPartial() {
        VisualSearchOuterClass.VisualSearchRequest result = new VisualSearchOuterClass.VisualSearchRequest(this);
        result.imageUrl_ = imageUrl_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VisualSearchOuterClass.VisualSearchRequest) {
          return mergeFrom((VisualSearchOuterClass.VisualSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VisualSearchOuterClass.VisualSearchRequest other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                imageUrl_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                text_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object imageUrl_ = "";
      /**
       * <code>string image_url = 1;</code>
       * @return The imageUrl.
       */
      public java.lang.String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image_url = 1;</code>
       * @return The bytes for imageUrl.
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        java.lang.Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_url = 1;</code>
       * @param value The imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 1;</code>
       * @param value The bytes for imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 2;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:visual_search.VisualSearchRequest)
    }

    // @@protoc_insertion_point(class_scope:visual_search.VisualSearchRequest)
    private static final VisualSearchOuterClass.VisualSearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VisualSearchOuterClass.VisualSearchRequest();
    }

    public static VisualSearchOuterClass.VisualSearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisualSearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<VisualSearchRequest>() {
      @java.lang.Override
      public VisualSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VisualSearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualSearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public VisualSearchOuterClass.VisualSearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VisualSearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visual_search.VisualSearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @return A list containing the similarImageUrls.
     */
    java.util.List<java.lang.String>
        getSimilarImageUrlsList();
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @return The count of similarImageUrls.
     */
    int getSimilarImageUrlsCount();
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @param index The index of the element to return.
     * @return The similarImageUrls at the given index.
     */
    java.lang.String getSimilarImageUrls(int index);
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the similarImageUrls at the given index.
     */
    com.google.protobuf.ByteString
        getSimilarImageUrlsBytes(int index);

    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @return A list containing the similarTextIds.
     */
    java.util.List<java.lang.Integer> getSimilarTextIdsList();
    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @return The count of similarTextIds.
     */
    int getSimilarTextIdsCount();
    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The similarTextIds at the given index.
     */
    int getSimilarTextIds(int index);
  }
  /**
   * Protobuf type {@code visual_search.VisualSearchResponse}
   */
  public static final class VisualSearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:visual_search.VisualSearchResponse)
      VisualSearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualSearchResponse.newBuilder() to construct.
    private VisualSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualSearchResponse() {
      similarImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      similarTextIds_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisualSearchResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_visual_search_VisualSearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_visual_search_VisualSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VisualSearchOuterClass.VisualSearchResponse.class, VisualSearchOuterClass.VisualSearchResponse.Builder.class);
    }

    public static final int SIMILAR_IMAGE_URLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList similarImageUrls_;
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @return A list containing the similarImageUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getSimilarImageUrlsList() {
      return similarImageUrls_;
    }
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @return The count of similarImageUrls.
     */
    public int getSimilarImageUrlsCount() {
      return similarImageUrls_.size();
    }
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @param index The index of the element to return.
     * @return The similarImageUrls at the given index.
     */
    public java.lang.String getSimilarImageUrls(int index) {
      return similarImageUrls_.get(index);
    }
    /**
     * <code>repeated string similar_image_urls = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the similarImageUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getSimilarImageUrlsBytes(int index) {
      return similarImageUrls_.getByteString(index);
    }

    public static final int SIMILAR_TEXT_IDS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList similarTextIds_;
    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @return A list containing the similarTextIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getSimilarTextIdsList() {
      return similarTextIds_;
    }
    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @return The count of similarTextIds.
     */
    public int getSimilarTextIdsCount() {
      return similarTextIds_.size();
    }
    /**
     * <code>repeated int32 similar_text_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The similarTextIds at the given index.
     */
    public int getSimilarTextIds(int index) {
      return similarTextIds_.getInt(index);
    }
    private int similarTextIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < similarImageUrls_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, similarImageUrls_.getRaw(i));
      }
      if (getSimilarTextIdsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(similarTextIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < similarTextIds_.size(); i++) {
        output.writeInt32NoTag(similarTextIds_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < similarImageUrls_.size(); i++) {
          dataSize += computeStringSizeNoTag(similarImageUrls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSimilarImageUrlsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < similarTextIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(similarTextIds_.getInt(i));
        }
        size += dataSize;
        if (!getSimilarTextIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        similarTextIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VisualSearchOuterClass.VisualSearchResponse)) {
        return super.equals(obj);
      }
      VisualSearchOuterClass.VisualSearchResponse other = (VisualSearchOuterClass.VisualSearchResponse) obj;

      if (!getSimilarImageUrlsList()
          .equals(other.getSimilarImageUrlsList())) return false;
      if (!getSimilarTextIdsList()
          .equals(other.getSimilarTextIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSimilarImageUrlsCount() > 0) {
        hash = (37 * hash) + SIMILAR_IMAGE_URLS_FIELD_NUMBER;
        hash = (53 * hash) + getSimilarImageUrlsList().hashCode();
      }
      if (getSimilarTextIdsCount() > 0) {
        hash = (37 * hash) + SIMILAR_TEXT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getSimilarTextIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VisualSearchOuterClass.VisualSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VisualSearchOuterClass.VisualSearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visual_search.VisualSearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visual_search.VisualSearchResponse)
        VisualSearchOuterClass.VisualSearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_visual_search_VisualSearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_visual_search_VisualSearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VisualSearchOuterClass.VisualSearchResponse.class, VisualSearchOuterClass.VisualSearchResponse.Builder.class);
      }

      // Construct using visual_search.visual_search.VisualSearch.VisualSearchResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        similarImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        similarTextIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_visual_search_VisualSearchResponse_descriptor;
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchResponse getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchResponse build() {
        VisualSearchOuterClass.VisualSearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public VisualSearchOuterClass.VisualSearchResponse buildPartial() {
        VisualSearchOuterClass.VisualSearchResponse result = new VisualSearchOuterClass.VisualSearchResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          similarImageUrls_ = similarImageUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.similarImageUrls_ = similarImageUrls_;
        if (((bitField0_ & 0x00000002) != 0)) {
          similarTextIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.similarTextIds_ = similarTextIds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VisualSearchOuterClass.VisualSearchResponse) {
          return mergeFrom((VisualSearchOuterClass.VisualSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VisualSearchOuterClass.VisualSearchResponse other) {
        if (other == getDefaultInstance()) return this;
        if (!other.similarImageUrls_.isEmpty()) {
          if (similarImageUrls_.isEmpty()) {
            similarImageUrls_ = other.similarImageUrls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSimilarImageUrlsIsMutable();
            similarImageUrls_.addAll(other.similarImageUrls_);
          }
          onChanged();
        }
        if (!other.similarTextIds_.isEmpty()) {
          if (similarTextIds_.isEmpty()) {
            similarTextIds_ = other.similarTextIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSimilarTextIdsIsMutable();
            similarTextIds_.addAll(other.similarTextIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSimilarImageUrlsIsMutable();
                similarImageUrls_.add(s);
                break;
              } // case 10
              case 16: {
                int v = input.readInt32();
                ensureSimilarTextIdsIsMutable();
                similarTextIds_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureSimilarTextIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  similarTextIds_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList similarImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSimilarImageUrlsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          similarImageUrls_ = new com.google.protobuf.LazyStringArrayList(similarImageUrls_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @return A list containing the similarImageUrls.
       */
      public com.google.protobuf.ProtocolStringList
          getSimilarImageUrlsList() {
        return similarImageUrls_.getUnmodifiableView();
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @return The count of similarImageUrls.
       */
      public int getSimilarImageUrlsCount() {
        return similarImageUrls_.size();
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param index The index of the element to return.
       * @return The similarImageUrls at the given index.
       */
      public java.lang.String getSimilarImageUrls(int index) {
        return similarImageUrls_.get(index);
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the similarImageUrls at the given index.
       */
      public com.google.protobuf.ByteString
          getSimilarImageUrlsBytes(int index) {
        return similarImageUrls_.getByteString(index);
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param index The index to set the value at.
       * @param value The similarImageUrls to set.
       * @return This builder for chaining.
       */
      public Builder setSimilarImageUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSimilarImageUrlsIsMutable();
        similarImageUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param value The similarImageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addSimilarImageUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSimilarImageUrlsIsMutable();
        similarImageUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param values The similarImageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addAllSimilarImageUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureSimilarImageUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, similarImageUrls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSimilarImageUrls() {
        similarImageUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string similar_image_urls = 1;</code>
       * @param value The bytes of the similarImageUrls to add.
       * @return This builder for chaining.
       */
      public Builder addSimilarImageUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSimilarImageUrlsIsMutable();
        similarImageUrls_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList similarTextIds_ = emptyIntList();
      private void ensureSimilarTextIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          similarTextIds_ = mutableCopy(similarTextIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @return A list containing the similarTextIds.
       */
      public java.util.List<java.lang.Integer>
          getSimilarTextIdsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(similarTextIds_) : similarTextIds_;
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @return The count of similarTextIds.
       */
      public int getSimilarTextIdsCount() {
        return similarTextIds_.size();
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @param index The index of the element to return.
       * @return The similarTextIds at the given index.
       */
      public int getSimilarTextIds(int index) {
        return similarTextIds_.getInt(index);
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @param index The index to set the value at.
       * @param value The similarTextIds to set.
       * @return This builder for chaining.
       */
      public Builder setSimilarTextIds(
          int index, int value) {
        ensureSimilarTextIdsIsMutable();
        similarTextIds_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @param value The similarTextIds to add.
       * @return This builder for chaining.
       */
      public Builder addSimilarTextIds(int value) {
        ensureSimilarTextIdsIsMutable();
        similarTextIds_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @param values The similarTextIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllSimilarTextIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSimilarTextIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, similarTextIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 similar_text_ids = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSimilarTextIds() {
        similarTextIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:visual_search.VisualSearchResponse)
    }

    // @@protoc_insertion_point(class_scope:visual_search.VisualSearchResponse)
    private static final VisualSearchOuterClass.VisualSearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VisualSearchOuterClass.VisualSearchResponse();
    }

    public static VisualSearchOuterClass.VisualSearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisualSearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<VisualSearchResponse>() {
      @java.lang.Override
      public VisualSearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VisualSearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualSearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public VisualSearchOuterClass.VisualSearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visual_search_VisualSearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visual_search_VisualSearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visual_search_VisualSearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visual_search_VisualSearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023visual_search.proto\022\rvisual_search\"6\n\023" +
      "VisualSearchRequest\022\021\n\timage_url\030\001 \001(\t\022\014" +
      "\n\004text\030\002 \001(\t\"L\n\024VisualSearchResponse\022\032\n\022" +
      "similar_image_urls\030\001 \003(\t\022\030\n\020similar_text" +
      "_ids\030\002 \003(\0052h\n\023VisualSearchService\022Q\n\006Sea" +
      "rch\022\".visual_search.VisualSearchRequest\032" +
      "#.visual_search.VisualSearchResponseb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_visual_search_VisualSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visual_search_VisualSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visual_search_VisualSearchRequest_descriptor,
        new java.lang.String[] { "ImageUrl", "Text", });
    internal_static_visual_search_VisualSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_visual_search_VisualSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visual_search_VisualSearchResponse_descriptor,
        new java.lang.String[] { "SimilarImageUrls", "SimilarTextIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
